# Site settings
title: Inter/sections 2017
email: info@intersections.io
description: > # this means to ignore newlines until "baseurl:"
  Inter/sections is an annual week-long event organised by the students of the Media and Arts Technology Program at Queen Mary University of London. During this week we 
  discuss relevant themes to art and technology practice through events, workshops, conversations, and a Symposium day where we foster exchange between aritsts, industry, 
  academia and activists.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: intersections_io
github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

plugins_dir: [jekyll-paginate]